### ISSUE TITLE
Reading the specific tempo/BPM of input MIDI files

### ISSUE THREAD

**Issue by shinysup** [craffel/pretty-midi#116]
Hello,

is there a way to not estimate, but simply load the preset value of tempo/BPM of the input MIDI files?

**Comment by craffel** [comment]
Yes, [get_tempo_changes](http://craffel.github.io/pretty-midi/#pretty_midi.PrettyMIDI.get_tempo_changes).  E.g.
```Python
import pretty_midi
pm = pretty_midi.PrettyMIDI('file.mid')
print pm.get_tempo_changes()
```
