### ISSUE TITLE
Picking out the melody (vocal) track

### ISSUE THREAD

**Issue by shinysup** [craffel/pretty-midi#118]
Is there a way to pick out the main melody (sung by vocal in the actual song but played by some other instrument in the file) track?

I'm thinking of picking out a track that plays consistently through the song and has single notes, but I have a feeling that it would be a hassle and was wondering if there is any other convenient way.

**Comment by craffel** [comment]
There's a relevant snippet from my [ISMIR 2016 paper](http://colinraffel.com/publications/ismir2016extracting.pdf):

> While the MIDI specification does include “track name”, “program name”, and “instrument name” metaevents, they are not standardized and so are not used consistently. It follows that there is no simple way to retrieve the “melody” from a MIDI transcription, although the fact that all instruments are transcribed separately can make its estimation more straightforward than for audio files. For example, [31] explores the use of simple features such as the average velocity and note range within a track to predict whether it is a melody, and also finds that in a small dataset the track name reliably indicates a melody track 44.3% of the time. Similarly, [23] uses heuristic features and a random forest classifier to predict with high accuracy whether a track is a melody.

If you reimplement or come up with a high-accuracy approach, I'd be happy to have it added to the examples directory.
