### ISSUE TITLE
chord progression

### ISSUE THREAD

**Issue by shinandrew** [craffel/pretty-midi#123]
I'm trying to extract one chord per bar (4 quarter notes),
and I'm reducing the pool to just major and minor chords, so no sus, aug, not even 7th.

My current approach is to find the most dominant pitch in the bass track, assume it's a root note, and find whether minor 3rd note is present in piano/keyboard track. If not, I assume it's a major chord.

For example, if the most dominant bass pitch is C in one whole bar length, I look for E# in keyboard track in that bar, and if present, then the chord becomes Cm, otherwise C.

Would this be a plausible approach, or is there a simpler way to do it?

**Comment by craffel** [comment]
It's non-trivial.  I would think any rule-based approach would have lots of failure modes.  There are some pointers [here](http://colinraffel.com/publications/ismir2016extracting.pdf) in section 2.6:

> Both music21 [9] and melisma [30] include functionality for estimating chord sequences from
symbolic data. Rhodes et al. [29] also proposed a symbolic chord estimation method using Bayesian Model Selection, which was shown to outperform melisma on a dataset of Beatles MIDI files in [14].
