### ISSUE TITLE
Bump Version

### ISSUE THREAD

**Issue by stefan-balke** [craffel/pretty-midi#124]
Hi Colin,

maybe you could please make a minor revision for pypi? The pypi version is not working with Python 3, the GitHub version is.

Well, at least I can read MIDI :)

**Comment by craffel** [comment]
I feel l was waiting for something before making a new release, but I can't remember what.  I am swamped right now but will do this soon.

**Comment by craffel** [comment]
Should be updated, want to double check all is ok for you on Py3?

**Comment by stefan-balke** [comment]
Thanks. Will report shortly.

**Comment by stefan-balke** [comment]
It's all working fine! Thanks, Colin!
