### ISSUE TITLE
Feature request: Piano roll to MIDI utility function

### ISSUE THREAD

**Issue by carlthome** [craffel/pretty-midi#125]
I realize this might be asking too much but [as discussed on the ISMIR mailing list](http://groups.google.com/a/ismir.net/group/community/t/31f96fe796a50398?utm_source=digest&utm_medium=email), it would be neat to have a way to convert piano rolls back to MIDI, directly in pretty-midi.

Perhaps each track could be kept in a third dimension of a piano roll, and each element could retain the velocity at least.

I'm doing something like this but only for a single track, at the moment:

```python
import numpy as np
from mido import MidiFile, MidiTrack, Message as MidiMessage

def piano_roll_to_midi(piano_roll, base_note=21):
    """Convert piano roll to a MIDI file."""
    notes, frames = piano_roll.shape
    midi = MidiFile()
    track = MidiTrack()
    midi.tracks.append(track)
    now = 0
    piano_roll = np.hstack((np.zeros((notes, 1)), 
                            piano_roll, 
                            np.zeros((notes, 1))))
    velocity_changes = np.nonzero(np.diff(piano_roll).T)
    for time, note in zip(*velocity_changes):
        velocity = piano_roll[note, time + 1]
        message = MidiMessage(
            type='note_on' if velocity > 0 else 'note_off', 
            note=int(note + base_note), 
            velocity=int(velocity * 127),
            time=int(time - now))
        track.append(message)
        now = time
    return midi
```

What I have a hard time getting right is the PPQ and tempo. My `midi_to_piano_roll` just implicitly assumes Mido's defaults at the moment, and that there are no tempo changes or control messages at all.

**Comment by craffel** [comment]
This has been high on my to-do list.  It would definitely be more appropriate in the `examples` directory, as their is no correct way to do this.  (I bet you are aware, but there is no way to get tempo, ppq, pitch bends, control changes, lyrics, etc. from a piano roll matrix, so handling all of that is a matter of choice/implementation).  If you are motivated to try to add an example of this yourself, I would be happy to see it.

**Comment by rafaelvalle** [comment]
I'm not sure how MidiMessage treats changes in positive velocity values, e.g. decrescendo or crescendo, but it should not imply a new articulation of the note.

**Comment by carlthome** [comment]
Yeah, as @craffel said going from/to a piano roll is lossy so it's a matter of choice. The snippet I posted is used for piano so changing velocity without articulating a note has never come up. 

Maybe just keep track of whether a key is down or up, e.g.:

```python
active = np.zeros(notes)
for time, note in ...:
    if not active[note]:
        active[note] = if velocity > 0
        # Create note_on or note_off here.
    else:
        # Create corresponding MIDI message for increased velocity here.
```

**Comment by rafaelvalle** [comment]
Here's a cumbersomely slow version. Note that unlike your example, I interpret piano rolls as Frame by Notes matrix, not Notes by Frames.

```
def pianoroll_to_midi(pianoroll, fs, program=1, filepath='midifile.mid'):
    # create PrettyMIDI object
    midifile = pm.PrettyMIDI()
    # create Instrument instance
    if type(program) is not int:
        program = pm.instrument_name_to_program(program)
    instrument = pm.Instrument(program=program)

    # cumbersomely slow
    for note in range(pianoroll.shape[1]):
        start = 0
        end = 0
        while end < pianoroll.shape[0]:
            # find where note starts
            while start < pianoroll.shape[0] and pianoroll[start, note] == 0:
                start += 1
            end = start + 1

            # nothing left
            if start == pianoroll.shape[0]:
                break

            # find where note ends
            while end < pianoroll.shape[0] and pianoroll[end, note] > 0:
                end += 1

            # add note to instrument
            instrument.notes.append(pm.Note(
                velocity=int(pianoroll[start, note]),
                pitch=note,
                start=start * 1.0/fs,
                end=end * 1.0/fs))
            start = end

    midifile.instruments.append(instrument)
    midifile.write(filepath)
```

**Comment by jsleep** [comment]
I created a PR (https://github.com/craffel/pretty-midi/pull/129) with this util in the examples folder. It is basically just @carlthome 's code adapted from Midos to pretty_midi.
