### ISSUE TITLE
PrettyMIDI.adjust_times should force times to be monotonic

### ISSUE THREAD

**Issue by craffel** [craffel/pretty-midi#126]
Right now, there is no check/enforcement that `original_times` and `new_times` be monotonically increasing.  This results in very strange behavior, like negative tempi, which causes later issues.  They should be tested for monotonicity; if they are not monotonic, a warning should be given and they should be made monotonic with `np.maximum.accumulate`.

**Comment by areeves87** [comment]
I've taken a crack at this issue with the above pull request. #145
