### ISSUE TITLE
Python 3 Incompatibility with estimate_tempo()

### ISSUE THREAD

**Issue by angusturner** [craffel/pretty-midi#128]
Calling the `estimate_tempo()` function on a Midi object in Python 3.6 throws the following error:

```
# Normalize all iois into the range 30...300bpm
--> 432         for n in xrange(ioi.shape[0]):
    433             while ioi[n] < .2:
    434                 ioi[n] *= 2

NameError: name 'xrange' is not defined
```

**Comment by craffel** [comment]
Fixed in c8ae1fae96bb3e2eec6f3ad360c691e43eb32247, thanks!

**Comment by bzamecnik** [comment]
Could you please make a release, even if it's a tiny fix? Last release 0.2.7 still does not contain this bug and fails in Python 3. Thank you.

**Comment by craffel** [comment]
Sorry, has been a busy time.  Making a new release now.

**Comment by craffel** [comment]
Ok, new version is up on pypi.  https://pypi.python.org/pypi/pretty_midi
