### ISSUE TITLE
get_piano_roll does not take the MIDI sustain CC into account

### ISSUE THREAD

**Issue by craffel** [craffel/pretty-midi#130]
MIDI CC 64 is the "sustain pedal" control channel.  If it's on, notes should be held until it's turned off.  get_piano_roll doesn't take this into account.

**Comment by maezawa-akira** [comment]
Hi, I added a flag to explicitly look at CC64.  It also contains a threshold pedal on/off, to allow handing of both standard MIDI pedal specs (CC64>64 is pedal on) versus continuous pedals (CC64>0 is soft pedal on).
