### ISSUE TITLE
How to slice the whole song up to 2-bar segments?

### ISSUE THREAD

**Issue by JeremyFxx** [craffel/pretty-midi#149]
When I read the midi file of a song using `pretty_midi.PrettyMIDI()`, the whole song is stored in a `pretty_midi.PrettyMIDI` object. However, I want to slice the whole song into 2-bar segments and store them into a list of `pretty_midi.PrettyMIDI` objects. 

My idea is:
1. First read the whole song and store it in a `pretty_midi.PrettyMIDI` object.
2. Because normally the bars are determined the time signature and the downbeats, use the `time_signature_changes()` and `get_downbeats()` to get the start time and end time of each "2 bars".
3. Use some functions to slice the `pretty_midi.PrettyMIDI` object that contains the whole songs into a list of  `pretty_midi.PrettyMIDI` objects according to the start time and end time of each "2 bars". 

My questions are:
1. Is there any function that can slice the `pretty_midi.PrettyMIDI` object into pieces?
2. Does my solution for slicing the song into 2-bar segments make sense or not?

**Comment by JeremyFxx** [comment]
Great! It works well. 
However, I encounter another problem. Because I want to slice the `pm` to hundred of pieces. But each time I use the `adjust_times` make the `pm` to a clip and losing other bars. So I try to copy the `pm` to a `pm_tmp` to do the `adjust_times`, but it seems that the copy is a shallow copy. Is there any solutions other than read the midi file to `pm` for hundred of times?
Thanks for you help.

**Comment by craffel** [comment]
`copy.deepcopy` should work.

**Comment by JeremyFxx** [comment]
Oh, that's it. Right now I think I already solve the problem. I will feed the slices to the dnn model to see whether they work as expected. I just leave this issue open for sometime in case of some relevant problems. Thank you very much for your wonderful library and kind help.

**Comment by craffel** [comment]
I'll close it for now, if someone has another question they can re-open.
