### ISSUE TITLE
Instrument uniqueness

### ISSUE THREAD

**Issue by EricCacciavillani** [craffel/pretty-midi#156]
Hi again! Trying to figure out a good way of solving this problem but wanted to ask for the best way of doing this.

In my project, I am looking at multiple instrument note pairs. The only problem is that there are multiple instruments and just because they have the same name doesn't mean that they are the same instrument 100% of the time. (It should be I know but from what I have been seeing is that people do slight modifications to each.)

I personally would like to analyze the instrument itself (like the extra data on just the instrument in question) and **not** the notes associated with it. Is that possible?

**Comment by EricCacciavillani** [comment]
I did try to raise fluidsynth on each instrument to see if I could learn something about each instrument but even after installation of the dependency, it threw the same error again...


`File "/home/eric/anaconda3/envs/LyreBird/lib/python3.6/site-packages/pretty_midi/instrument.py", line 416, in fluidsynth
    raise ImportError("fluidsynth() was called but pyfluidsynth "
ImportError: fluidsynth() was called but pyfluidsynth is not installed.`

**Comment by EricCacciavillani** [comment]
I think I figured out the problem it was simply the program number that represents the proper instrument.

**Comment by EricCacciavillani** [comment]
Found it! 
program_to_instrument_class

**Comment by gongel** [comment]
How did you fix it?
