### ISSUE TITLE
fluidsynth has no attribute Synth

### ISSUE THREAD

**Issue by EricCacciavillani** [craffel/pretty-midi#157]
I have fluidsynth throwing this error when I call it on my instrument obj.

<img width="1536" alt="screen shot 2019-01-05 at 12 22 04 am" src="https://user-images.githubusercontent.com/16104771/50720728-6d78c380-1080-11e9-9f44-c7f70858095c.png">

**Comment by EricCacciavillani** [comment]
No, not that I know of...
I have this as my version of  pyFluidSynth==1.2.5...is that the right version????

**Comment by craffel** [comment]
Yes, that should be fine. I just confirmed that the fluidsynth on PyPI has the Synth class:
https://pypi.org/project/pyFluidSynth/#files
(you can check by downloading the .tar.gz)
You can check that you are importing the right thing by checking what `fluidsynth.__file__` is and confirming that it's the fluidsynth library you installed.

**Comment by EricCacciavillani** [comment]
I believe you. I am going to try playing around and report back my findings. Thank you as always for the help.

**Comment by EricCacciavillani** [comment]
Fix one bug pass it around....another little bug pops up...Lol.
You were of course right another test I was running awhile back was using a fluidsynth name convention. But now it is telling it is not installed...
<img width="1536" alt="screen shot 2019-01-05 at 2 48 07 pm" src="https://user-images.githubusercontent.com/16104771/50728535-3692c400-10f9-11e9-9c13-08f5931f1ad2.png">
 

<img width="1536" alt="screen shot 2019-01-05 at 2 47 24 pm" src="https://user-images.githubusercontent.com/16104771/50728513-ed427480-10f8-11e9-989a-1e6e4608bec2.png">

**Comment by craffel** [comment]
I am guessing there is some issue with your Python paths - you may have two different distributions/paths where Python packages are being installed.

**Comment by EricCacciavillani** [comment]
Hmmm not a bad idea/thought. Just downloaded it to every enviorment to see if that was the case and checked the pip/python paths were right...still a no go...

Well let me just ask this then. Does pyfluidsynth create any synthesized form for drum instruments? If no then it won't matter to me and I'll just use your default synthesizer.

Reason being is I am currently graphing the instruments/note pairs found and I am using Hz of the notes, the synthesized form of instrument note pair (I convert it to one value dont ask nerd math ;p), and I would look to chose another value but still working on that...

The problem is that drums returns zeros (which I get). But in the pretty midi docks it didnt explicity say that "Will return zeros if drums." so the hopeful part of me wanted to give it a shot and pray that it worked.

**Comment by craffel** [comment]
Yes, fluidsynth should synthesize drums with the soundfont included with pretty_midi.

**Comment by EricCacciavillani** [comment]
YES!!! THATS AWESOME!....NOW TO FIGURE OUT WHAT THE HELL I HAVE DONE WRONG!

**Comment by craffel** [comment]
You need to install both pyfluidsynth and the fluidsynth program (installable, for example, via https://formulae.brew.sh/formula/fluid-synth )

**Comment by EricCacciavillani** [comment]
Hmm, haven't tried getting brew for Ubuntu yet. Might as well give it a shot. (Ubuntu server)

**Comment by craffel** [comment]
You can just run `apt-get install fluidsynth`.
https://github.com/FluidSynth/fluidsynth/wiki/Download#distributions

**Comment by EricCacciavillani** [comment]
Lol you said that right as I got brew working. But that saves an extra line of code so why not. Thank you. It seems to work. I have to see how pyfluidsynth works now. Entirely my fault for assuming the fluidsynth could be installed with pip. (There is a fluidsynth lib so I assumed that was it without actually clicking on the link thanks again!)

**Comment by Abdelrahman-kamall** [comment]
Hi,
sorry to reopen this issue but because I'm having the exact error and i couldn't solve it yet , 

, actually I thought that the problem is that the **/pretty_midi/instrument.py** file has a function called the same name as the imported package which is **fluidsynth** 
when i just click it on GitHub it links it to the function name and not the package imported , that's why i thought this is the problem ,
![image](https://user-images.githubusercontent.com/45362684/106471321-2c934900-64aa-11eb-92c0-31a3117ebda1.png)

i am using google colab and i used 
`!pip install  fluidsynth`
i also install the pyfluidsynth
`!pip install  pyfluidsynth==1.3.0`
from following this issue i think this is not the correct way to install it right  ? if so can u help me with how to install it on colab ?

Thank you in advance
