### ISSUE TITLE
Add bibtex entry

### ISSUE THREAD

**Issue by Datseris** [craffel/pretty-midi#162]
Hi,

if you want your paper to be citable easily please add a proper bib tex entry to your README.

**Comment by craffel** [comment]
https://scholar.googleusercontent.com/scholar.bib?q=info:H-IAznloIgEJ:scholar.google.com/&output=citation&scisig=AAGBfm0AAAAAXHQvfocETT0pIFekaK7gAJ91O4ZFVVJ6&scisf=4&ct=citation&cd=-1&hl=en&scfhb=1
