### ISSUE TITLE
key signature error

### ISSUE THREAD

**Issue by mmoayeri** [craffel/pretty-midi#165]
hello, is it possible to override the key signature error thrown when a single key signature cannot be decoded? I am working with some improvisational files with many accidentals (flats, sharps) that may not have a particular key or change keys rapidly. I don't make use of the key signature field, so it is unfortunate that I cannot make pretty midi objects for many of my files bc of a property I won't be using.

The exact exception is 'Could not decode key with 18 flats and mode 1'. the key information could also just be corrupted, but again, I would like to ignore this if possible.

Many thanks for your great work.

**Comment by craffel** [comment]
This is an error raised by mido, not pretty_midi:
https://github.com/mido/mido/blob/2a3c811e591ce3d394174e62ab30ba89a3cdf278/mido/midifiles/meta.py#L396
Can you just remove the corrupt key signatures from your files before reading them?
