### ISSUE TITLE
Plot grid according to given beat divisions 

### ISSUE THREAD

**Issue by jabrennem** [craffel/pretty-midi#167]
Hi, 

I really enjoy pretty-midi. I had a question that I could not find in the documentation. 

On the jupyter notebook tutorial that you supplied, there is really helpful code for plotting the denominator value beat supplied by the time signature (quarter note for 4/4, etc.) and down beats (1st beat of a measure) against the piano roll using get_beats() and get_downbeats() respectively (shown below).

~~~~python
# Get and downbeat times
beats = pm.get_beats()
downbeats = pm.get_downbeats()
# Plot piano roll
plt.figure(figsize=(12, 4))
plot_piano_roll(pm, 24, 84)
ymin, ymax = plt.ylim()
# Plot beats as grey lines, downbeats as white lines
mir_eval.display.events(beats, base=ymin, height=ymax, color='#AAAAAA')
mir_eval.display.events(downbeats, base=ymin, height=ymax, color='#FFFFFF', lw=2)
# Only display 20 seconds for clarity
plt.xlim(25, 45);
~~~~

How would you plot 16th/32nd/64th notes against the same plot? Is there a way to create a piano roll DataFrame where the number of columns reflects these note divisions? 

~~~~python
# pseudo code for 32nd note example
times = []  # this would be a list of locations in seconds where each column is 
            # a 32th note distance away from each other taking into account 
            # changing time signatures
velocity_df = instrument.get_piano_roll(times=times)
velocity_df.shape
(127, number of 32nd notes in the track)
~~~~

If I transposed velocity_df, I could know the tempo and time signature of a given row based on the times list even though each row represents a 32nd note.

**Comment by craffel** [comment]
If you assume that e.g. 16th notes subdivide each beat into fourths, you can do something like
beats = pm.get_beats()
np.interp(np.arange(beats.shape[0]*4), np.arange(0, beats.shape[0]*4, 4), beats)
I don't know how to interface that with pandas.
