### ISSUE TITLE
Print notes as PianoRoll

### ISSUE THREAD

**Issue by AlterB** [craffel/pretty-midi#171]
hi, 
i need to print the notes inside a midi file like pianoroll.
How can i do this?

Thanks

**Comment by craffel** [comment]
What do you mean by "print like pianoroll"? Piano rolls are usually displayed as images. See `pretty_midi.PrettyMIDI.get_piano_roll` or the Tutorial https://github.com/craffel/pretty-midi/blob/master/Tutorial.ipynb

**Comment by AlterB** [comment]
Thanks! I didn't see the tutorial!
