### ISSUE TITLE
Allow note positions to be in absolute ticks. 

### ISSUE THREAD

**Issue by johncwok** [craffel/pretty-midi#172]
Hi ! I think it would be a very usefull feature for your code to allow it to take in (and return) position values in absolute ticks. When carrying analysis, or doing machine learning, having time in seconds can be a drawback because the rythmic value gets lost.

**Comment by craffel** [comment]
You can convert any time (such as a note's start or end time) to ticks using `pretty_midi.PrettyMIDI.time_to_tick`.
