### ISSUE TITLE
Pretty_midi returns negatvie notes positions

### ISSUE THREAD

**Issue by johncwok** [craffel/pretty-midi#173]
I am trying to process a database of MIDI jazz solos, and I noticed that the package pretty_MIDI returns negative onset times for the following MIDI piece : https://jazzomat.hfm-weimar.de/dbformat/synopsis/solo80.html

My code is the following : 
```
In [69]: test = pretty_midi.PrettyMIDI("..\\data\\MIDI\\ChrisPotter_InASentimentalMood_FINAL.mid")
In [70]: test.instruments[0].notes[0:5]
Out[71]: 
[Note(start=-55.439009, end=-56.204049, pitch=53, velocity=82),
 Note(start=-56.371366, end=-57.487040, pitch=55, velocity=80),
 Note(start=-57.647156, end=-57.927275, pitch=56, velocity=84),
 Note(start=-57.977676, end=-59.400897, pitch=57, velocity=84),
 Note(start=-59.503070, end=-60.857834, pitch=60, velocity=93)]
```

Do you know what is going on ?

**Comment by craffel** [comment]
This is because `mido` reports the file as having a `ticks_per_beat` of -10096:
```Python
t = mido.MidiFile("ChrisPotter_InASentimentalMood_FINAL.mid")
print(t.ticks_per_beat)
```
gives `-10096`. The MIDI file probably has a corrupt header. You can either fix the header or see if there's a way to make `mido` more robust to this issue.

**Comment by johncwok** [comment]
Ok thanks for you reply !

I guess i'll just delete all the files of the database that are corrupt in
this manner because there are not that much anyway.

Best,

Corentin
