### ISSUE TITLE
Specifying soundfont instrument preset when using fluidsynth

### ISSUE THREAD

**Issue by lbros96** [craffel/pretty-midi#183]
Apologies if this something obvious I am missing about the .sf2 file format, but how do you specify which instrument preset to using just the .sf2 file path for the PrettyMidi.fluidsynth() function.

For example, when trying to synthesize a midi file using the MuseScore_General soundfont which has 128 instrument presets, how do I specify a particular instrument preset that I want to use? Thank you!
`audio = midi_data.fluidsynth(fs=16000, sf2_path = "******/Soundfont/MuseScore_General.sf3")`

**Comment by craffel** [comment]
Do you mean the different program numbers? The corresponding program will be chosen depending on the program of the `pretty_midi.Instrument`.
