### ISSUE TITLE
Midi files have two tracks, cannot be played on some midi devices

### ISSUE THREAD

**Issue by essandess** [craffel/pretty-midi#185]
The MIDI files produced by `pretty-midi` contain two tracks—the initial track is all meta messages—that prevents them from being played on some MIDI devices, a Yamaha piano for example. I believe that this behavior is a bug, and that `pretty-midi` should output single-track files unless otherwise specified.

For example, here is the output from a `pretty-midi` produced file, observed from `mido`:

```python
mid = mido.MidiFile('piano_test_pretty-midi.mid')                     

for i, trk in enumerate(mid.tracks): 
    print('Track {}: {}'.format(i, track.name)) 
    for msg in [msg for msg in trk if msg.is_meta]: 
        print(msg) 
```

> ```
> Track 0: Johann Sebastian Bach, Goldberg Variations 01: Aria
> <meta message set_tempo tempo=500000 time=0>
> <meta message time_signature numerator=4 denominator=4 clocks_per_click=24 > notated_32nd_notes_per_beat=8 time=0>
> <meta message end_of_track time=1>
> Track 1: Johann Sebastian Bach, Goldberg Variations 01: Aria
> <meta message end_of_track time=1>
> ```

It is possible to hack the `pretty-midi` output using `mido` to produce a playable single-track file with all meta messages, though this should be unnecessary:
```python
mid = mido.MidiFile('orig.mid')
mid_test = mido.MidiFile()
track = mido.MidiTrack()
mid_test.tracks.append(track)
for i, trk in enumerate(mid.tracks):
    if i == 0:
        for msg in trk:
            if msg.is_meta:
                if msg.type == 'end_of_track':
                    continue
                track.append(msg)
    elif i == 1:
        for msg in trk:
            track.append(msg)
    else:
        break
mid_test.save('piano_test.mid')
```

Code used to create `pretty-midi` file from source MIDI:
```python
orig_data = pretty_midi.PrettyMIDI('orig.MID')
piano_test = pretty_midi.PrettyMIDI()
piano_program = pretty_midi.instrument_name_to_program('Acoustic Grand Piano')
piano = pretty_midi.Instrument(program=piano_program)
for note in orig_data.instruments[0].notes:
    piano.notes.append(note)
piano_test.instruments.append(piano)
piano_test.write('piano_test.mid')
```

**Comment by craffel** [comment]
`pretty_midi` does not support writing to type 0 MIDI files. Many type 1 MIDI files use the format that `pretty_midi` uses, namely that meta-events appear on track 0 and playback events happen on other tracks. I do not plan to add support for type 0 MIDI files since it is an inherently (and unnecessarily) limited format, but would welcome a pull request for backwards compatibility.

**Comment by essandess** [comment]
@craffel Thanks for the pointer, and thanks for your work on Magenta.

I figured out how to convert MIDI files (`pretty_midi` or other) so that they’re playable on a Yamaha Modus: https://github.com/essandess/midi-yamaha-modus-converter

Magenta’s transcription quality is excellent—Gould’s Bach from Magenta is highly musical and enjoyable.
