### ISSUE TITLE
Setting or changing Tempo of a Midifile

### ISSUE THREAD

**Issue by soorejmg** [craffel/pretty-midi#186]
Hi,
Is there an option to set or change the tempo of a midi file available?. Could you let know the way for this. Couldnt see anything other than seeing the estimated tempo in the document. Please advice

Thanks
Soorej

**Comment by craffel** [comment]
You can use `adjust_times`. There is no other way to change the tempo directly and have the event times update automatically.

**Comment by soorejmg** [comment]
Hi,
Is there an example how to do this?. Could not really understand it from the document. Please provide if you have any. 
Thanks
Soorej

**Comment by craffel** [comment]
The tutorial provides an example: https://nbviewer.jupyter.org/github/craffel/pretty-midi/blob/master/Tutorial.ipynb#Adjusting-timing

**Comment by soorejmg** [comment]
Hi, Thanks for this details. While trying to change the tempo,  noticed some error in the tempo reading. Not sure whether the understandin is right, when i slow down the music , the tempo is increasing, while it should be a low speed music. For example, 
my intiital tempo was 162 (assuming bps), Then i slowed down using adjust_time to 1.4 times of initial, but then it shows 214. The tempo should have been a lesser value. Please advice
Thanks
Soorej

**Comment by craffel** [comment]
Can you post code?

**Comment by soorejmg** [comment]
![image](https://user-images.githubusercontent.com/47497915/94278458-693fb880-ff7d-11ea-8130-738ae21ab9fd.png)


tempo_final    
Out[241]: 214

tempo    
Out[242]: 162

**Comment by craffel** [comment]
Don't use estimate_tempo; it will produce a (possibly incorrect) estimate and is only intended for files that do not have tempo change events annotated. Use get_tempo_changes.

**Comment by soorejmg** [comment]
Hi, 
Thanks Craffel. It works. :)

Thanks
Soorej
