### ISSUE TITLE
Removing tempo changes

### ISSUE THREAD

**Issue by sid0710** [craffel/pretty-midi#191]
This is more of a question than an issue. I am working with midi files which have multiple tempo changes. I want to remove the tempo changes and adjust the notes to a constant tempo throughout. Is it possible to do this using pretty-midi? 
It would be really helpful if you could point me in the correct direction regarding this.

**Comment by craffel** [comment]
This is not supported directly in pretty_midi - you should remove the tempo change events with another library (say, mido) before loading the midi file into pretty_midi.
