### ISSUE TITLE
Adding key signature to file?

### ISSUE THREAD

**Issue by xhevahir** [craffel/pretty-midi#197]
This is more question than issue, but for some reason I can't figure out how to add a key signature to a MIDI file that has no such meta message at present. (I only need to add a single key indication, at the beginning.) Sorry to ask such a basic question, and thanks for any help.

**Comment by craffel** [comment]
You can do something like
```Python
import pretty_midi
pm = pretty_midi.PrettyMIDI("file.mid")
pm.key_signature_changes.insert(0, pretty_midi.KeySignature(key_number=0, time=0.0))
pm.write("file_with_key.mid")
```
