### ISSUE TITLE
Init with mido object parameter

### ISSUE THREAD

**Issue by mbobcik** [craffel/pretty-midi#200]
Hi,
I started working with this library and I noticed it uses mido. 
In my project I have mido objects and I would like to use pretty_midi functions on them.
Instead of saving it to temporary midi file and loading it again, possibility to pass the mido object to PrettyMidi would speed up things.
Or is there any other way I'm not aware of? 

My intention is to select just one track from midi file and generate chroma from it.

**Comment by craffel** [comment]
That's not currently supported, but it would make sense to support.
