### ISSUE TITLE
Request master branch be renamed to main

### ISSUE THREAD

**Issue by vrobertbaruch** [craffel/pretty-midi#202]
As part of Google's problematic terminology removal effort, many github repos are changing the name of their primary branch from master to main. Other projects referencing the master branch on this repo are blocked from their own problematic terminology removal. Can you please help by doing this renaming for your repo?

github has a tool which makes this change easy and backwards-compatible. See the [walkthrough](https://docs.github.com/en/github/administering-a-repository/managing-branches-in-your-repository/renaming-a-branch#renaming-a-branch).
* The base branch for all open pull requests will automatically change to the new branch name.
* Any URLs with the old branch name are automatically redirected to the new branch name.
* People visiting the repo will be notified that the main branch has changed.

**Comment by craffel** [comment]
Sure, done.
