### ISSUE TITLE
Add `length` to get the entire duration of midi, similar to `get_end_time`

### ISSUE THREAD

**Issue by jonata** [craffel/pretty-midi#203]
Hi!

I see some discussion on #80. I see that `get_end_time` does not give me the duration of the midi file in some cases. For a reference, if you look at `mido` `length` property, it would calculate all messages' times to get the desired duration value. What about adding this `length` property just [like `mido` does](https://github.com/mido/mido/blob/b884bc3c41d64da77bf6f3c879f823626c188e89/mido/midifiles/midifiles.py#L375)?

Thanks!

**Comment by craffel** [comment]
The get_end_time does exactly that - it provides the time of the final event (across all event types). The issue you linked was proposing that get_end_time only operate on note events.

**Comment by jonata** [comment]
Sorry, but in my tests I am getting different results using `get_end_time` and `mido`'s `length`. So `get_end_time` does not do "exactly that".
