### ISSUE TITLE
get piano roll with the right sampling rate

### ISSUE THREAD

**Issue by BaptisteLoquette** [craffel/pretty-midi#210]
Hello, hope you're doing well.
When using the get_piano_roll() function, the sampling rate it set by default to 100, but for many midi files it doesn't fit good. When using the piano_roll_to_pretty_midi() function we can see a lot of changes in comparison with the original MIDI file.

How to get the right sampling rate ? I can't find a function to get the sampling rate of the initial MIDI file through pretty midi or Mido. Can you help me please ?

Thanks

**Comment by BaptisteLoquette** [comment]
Okay I see, but from the tempos could I determine the best sampling rate ?

**Comment by craffel** [comment]
You could, but it would vary over the course of the MIDI file.

**Comment by craffel** [comment]
piano_roll_to_pretty_midi is an approximate/example function - you should not use it for anything except for fun.

**Comment by BaptisteLoquette** [comment]
Okay I see, but get_piano_roll() can be used no just for fun right ?

**Comment by craffel** [comment]
Depends on your definition of fun, I guess. It should only be used in settings where using a fixed sampling rate for the entire MIDI file is appropriate/workable.

**Comment by BaptisteLoquette** [comment]
I see, thanks for all your answers, I really appreciate that. Supposing a constant tempo how could I determine the best sampling rate pls ? If you don't have time to answer could you give me some references on the subject pls ?

**Comment by craffel** [comment]
You'll need to set it according to the pulses per quarter note and the tempo - you can start with https://en.wikipedia.org/wiki/Pulses_per_quarter_note. I will leave derivation of the exact formula up to the reader :)
