### ISSUE TITLE
Trim Silence

### ISSUE THREAD

**Issue by Mannerow** [craffel/pretty-midi#212]
Hello, 

I'm just wondering how you would suggest trimming silence on MIDI files? I have lots of data where I would like to remove silence from the start and end. 

The only method I've found online involves converting to a piano_roll, however, there doesn't seem to be a function to convert back from a piano roll to PrettyMIDI. 

I can see that the PrettyMIDI files have functions for getting the starting/ending time (estimate_beat_start, get_end_time). Is there any way to use these methods and change the MIDI file so that it only contains data in between the starting/end time? 

Thanks

**Comment by craffel** [comment]
You can use `get_end_time` to get the time of the final event: https://github.com/craffel/pretty-midi/blob/main/pretty_midi/pretty_midi.py#L441 and make an almost-identical function (doing a `min` instead of a `max`) to get the start time. Then, you can do `adjust_times([0, end_time - start_time], [start_time, end_time])`.

**Comment by Mannerow** [comment]
Thanks, @craffel. I appreciate it!

**Comment by Mannerow** [comment]
Here's how I ended up trimming the starting silence (just the reverse of what you said): 

![image](https://user-images.githubusercontent.com/47371658/178078410-fcd5dca1-b902-4f52-8b5a-eb3bbe7c0680.png)

Now I'm working on removing any silent bars, and I'm finding it a bit tricky. It seems like adjust_times isn't the best choice for this, since I actually want to cut these silences out completely. So, I'm trying to do it by iterating through each downbeat, converting this into an index into the piano_roll, and then deleting every section of the piano_roll that doesn't have any notes. 

Here is my code: 

![image](https://user-images.githubusercontent.com/47371658/178078583-7e1b5fcc-4a6a-4c07-8645-13d1911598bb.png)

So far, this isn't working. Does anyone have any suggestions or maybe an easier way to do this?
