### ISSUE TITLE
Bump version + new pip package

### ISSUE THREAD

**Issue by kevinzakka** [craffel/pretty-midi#218]
Hi Colin, would it be possible to bump the version and push a new version to PyPI?

**Comment by craffel** [comment]
For sure - just buried under a giant todo list. Will try to get to it soon.

**Comment by rithvik-doshi** [comment]
Would also appreciate this when possible, I'm using numpy >=1.24 and pretty-midi 0.2.9 and am getting the same error as in issue #205 but I understand if it'll take some time to do :)

**Comment by craffel** [comment]
Done.
