### ISSUE TITLE
Remove midi dependency

### ISSUE THREAD

**Issue by craffel** [craffel/pretty-midi#22]
Make pretty_midi able to do the MIDI data parsing, too

**Comment by carlthome** [comment]
Yes, please. python-midi lacks Python 3 support on PyPI (though there is a dev branch with Python 3 support on their GitHub repo) making setup.py installs complicated.

**Comment by Conchylicultor** [comment]
Or use mido for the low level parsing. The development is more active than python-midi and at least it's python 3 compatible.

**Comment by craffel** [comment]
This was resolved in #101, though this issue is more focused on creating a `pretty-midi`-native parser.  I don't think there's a strong reason for this except speed, which is addressed in #102.
