### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by jimtal001** [craffel/pretty-midi#251]
**here is the pip error:** I am trying to install in VSCode on windows.

PS C:\projects\SPEC2MIDI> pip install pretty_midi
Collecting pretty_midi
  Using cached pretty_midi-0.2.10.tar.gz (5.6 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: C:\Users\jimta.JIMTAL001\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

**note: This is an issue with the package mentioned above, not pip.**
hint: See above for details.

**Comment by craffel** [comment]
The error is
>  ERROR: Can not execute setup.py since setuptools is not available in the build environment.

This is unrelated to pretty_midi.

**Comment by jimtal001** [comment]
Thanks
