### ISSUE TITLE
Allow the user to adjust the tempo over time

### ISSUE THREAD

**Issue by craffel** [craffel/pretty-midi#28]
Currently, tick_scales and tick_to_time are functionally read-only.  Making this change will require a good deal of legwork.

**Comment by douglaseck** [comment]
+1 on this. I'm tempted to modify pm._PrettyMIDI__tick_scales. This makes me feel dirty inside, and will eventually break things. But hey, I need to create a tempo map in a midi file. I'll look into doing it with pymidi.

**Comment by craffel** [comment]
What's your end application?  For me, when I need to warp a MIDI file's timing to an arbitrary timebase, I find adjusting the time of the events and discarding tempo information (see `adjust_times`) works best.  The other option would be to insert lots and lots of tempo change events, but that would get totally insane for smoothly varying timebases pretty quickly, so I decided not to do that.  Of course, it would be nice in general to be able to tell pretty_midi that there should be a new single tempo change at time x to tempo y and have it adjust everything's timing.  It would just get kind of hairy to implement, I think, which is why I haven't done it yet.  In general, it would be nice to have a way to quickly retrieve time-in-seconds of different events while still maintaining ticks/bar position, but that's also pretty hairy to implement..!

**Comment by douglaseck** [comment]
I was looking for a lossless way to go back and forth from pretty midi to a
Google proto. But in the end I don't think it's that important. I can live
with losing the relationship between ticks/bar position for what Iim doing.

**Comment by craffel** [comment]
Arguably resolved by 5a6fadd7e8a69db1f737d2f1ff0ff4415a904ee8.
