### ISSUE TITLE
Additional features for key/time signatures

### ISSUE THREAD

**Issue by craffel** [craffel/pretty-midi#40]
cc @rafaelvalle 

I'm writing unit tests for the whole library, and found a few things I think should be changed/fixed with the time/key signature changes.

1. They currently aren't being written out in `PrettyMIDI.write`; they should be included here.  I started to do this myself, but I was unsure how to convert from our `KeySignature`/`TimeSignature` to python-midi data/events.

1. Related - I think it would be useful, for writing out any maybe in general, if `midi_key_to_key_number` got moved to a separate function in `utilities.py` and called something like  `mode_accidentals_to_key_number`; instead of taking in a `midi.event.KeySignature` it would just take in `num_accidentals` and `mode`.  Then, we should also have a `key_number_to_mode_accidentals`, which will be handy for writing out, I think.

1. `midi_key_to_key_number` and `key_name_to_key_number` don'tt have a Returns section in their docstring, I overlooked this when merging.

1. When constructing a PrettyMIDI object without a MIDI file, `key_changes` and `time_signature_changes` aren't getting created because they're created in the `_load_metadata` function which isn't called in that case.  So, we need to create empty lists for them manually, as is done for instruments; https://github.com/craffel/pretty-midi/blob/master/pretty_midi/pretty_midi.py#L96

I'll update if I find anything else!

**Comment by rafaelvalle** [comment]
Can I make these changes myself?

**Comment by craffel** [comment]
Please do if you're up for it!

**Comment by craffel** [comment]
Resolved in #42
