### ISSUE TITLE
Unused function arguments in get_pitch_class_histogram()

### ISSUE THREAD

**Issue by douglaseck** [craffel/pretty-midi#53]
https://github.com/craffel/pretty-midi/blob/master/pretty_midi/pretty_midi.py#L617
The arguments use_velocity and use_duration aren't passed through from pretty_midi.py to each instrument.

**Comment by douglaseck** [comment]
Similar issue for get_pitch_class_transition_matrix().

**Comment by craffel** [comment]
> The arguments use_velocity and use_duration aren't passed through from pretty_midi.py to each instrument.

Good catch, fixed in b1124b6a99959cce40e01b6c9dbecf747ba713c5!

> Similar issue for get_pitch_class_transition_matrix().

Not sure what you mean - `get_pitch_class_transition_matrix` only has one argument, `normalize`, which doesn't make a lot of sense to pass on (I don't think, anyways).

**Comment by douglaseck** [comment]
Oh I see. It's just a documentation bug. In pretty_midi.py    
def get_pitch_class_transition_matrix(self, normalize=False)
is documented to have two parameters: use_duration and normalize. But only normalize is present.

**Comment by craffel** [comment]
> Oh I see. It's just a documentation bug. In pretty_midi.py

Very true.  Fixed in 843c3af0018e36ff44c97728b349094bcfa670fb
