### ISSUE TITLE
get_pitch_class_transition_matrix returns unexpected results for some sequences.

### ISSUE THREAD

**Issue by douglaseck** [craffel/pretty-midi#54]
It's hard to do simple next-note transition probabilities using get_pitch_class_transition_matrix for certain midi files.

This sequence:
  Note(start=0.000000, end=0.200000, pitch=60, velocity=100)
  Note(start=0.250000, end=0.450000, pitch=61, velocity=100)
  Note(start=0.500000, end=0.700000, pitch=60, velocity=100)
  Note(start=0.750000, end=0.950000, pitch=62, velocity=100)
  Note(start=1.000000, end=1.200000, pitch=67, velocity=100)
Yields get_pitch_class_transition_matrix()
[[ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]

By only changing the offset time (making the notes less staccato) I get different results:
  Note(start=0.000000, end=0.237500, pitch=60, velocity=100)\
  Note(start=0.250000, end=0.487500, pitch=61, velocity=100)
  Note(start=0.500000, end=0.737500, pitch=60, velocity=100)
  Note(start=0.750000, end=0.987500, pitch=62, velocity=100)
  Note(start=1.000000, end=1.237500, pitch=67, velocity=100)
Yields get_pitch_class_transition_matrix()
[[ 0.  1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]

This is due to the use of a hardcoded time_thresh:
        # use 20hz(0.05s) as the maximum time threshold for transitions
        time_thresh = 0.05

I imagine this is desired behavior for more complicated files.  I believe the right thing to do is to compute vertical grouping first (chunking nearby notes into chords based on a time threshold) and then in a seconds step calculate next-note transition probabilities by moving horizontally through the chunked sequence. I guess you still might want to drop a transition based on a long pause. But in many kinds of music this is an odd claim to make. It amounts to claiming that a staccato performance of a piece should yield different note transition probabilities than the same piece played legato.

I don't think this warrants a fix(!) I just wanted to communicate my thoughts. Feel free to close out "Working as intended"

**Comment by craffel** [comment]
I think @rafaelvalle's rationale behind this threshold is that a "transition" means two notes that _immediately_ follow one another, modulo psychoacoustic temporal resolution (~50ms).  I'd just suggest we make that threshold user-settable.

**Comment by rafaelvalle** [comment]
Yes, making the threshold user-settable is indeed a good idea. I'm submitting a pull request.
@douglaseck note that transitions are added whenever the end of a note is within time_thresh from the start of any other note. This is musically odd, i.e. 4 voice chorale. It would be beneficial to implement get_pitch_class_transition_probabilities based on voice leading.
Issued a pull request.

**Comment by douglaseck** [comment]
I see. So, conceptually, all notes in a chord should get grouped
together? I think I misunderstood what this function was supposed to do. I
was thinking this as more about melodic groupings (horizontally i.e. over
time, rather than vertical (nearly-simultaneous events). What I wanted to
use this for was building simple n-gram models of melodies.  But I noticed
if the melodies were staccato, they weren't grouped whereas if they were
legato they did get grouped. Anyway that might be a different function.  I
think of vertical chunking (chords, etc) as being conceptually different in
music than horizontal organization (melodic effects, voice leading, etc)
 Agreed? I think this is pretty important so worth some discussion, though
maybe not here. :-)

**Comment by craffel** [comment]
> I see. So, conceptually, all notes in a chord should get grouped
together? I think I misunderstood what this function was supposed to do. I
was thinking this as more about melodic groupings (horizontally i.e. over
time, rather than vertical (nearly-simultaneous events).

Not quite, this function is indeed for notes which follow one another (horizontally), it's just that this function was specifically for designed for notes which immediately follow one another in time.  If you have a melodic instrument (no overlapping notes), and you only care about notes that follow one another regardless of how far apart, a good four-liner would be
```Python
instrument.notes.sort(lambda note: note.start)
transition_matrix = np.zeros((12, 12))
for start_note, end_note in zip(instrument.notes[:-1], instrument.notes[1:]):
    transition_matrix[start_note.pitch % 12, end_note.pitch % 12] += 1
```
Of course, if your instrument has any overlapping notes, this doesn't make much sense, but there you go.

**Comment by craffel** [comment]
@douglaseck #56 is merged, does that and the code snippet above do the trick for you?  If so, feel free to close.
