### ISSUE TITLE
Don't create a time signature by default when time signatures are present

### ISSUE THREAD

**Issue by craffel** [craffel/pretty-midi#61]
As reported by @douglaseck [here](https://github.com/craffel/pretty-midi/issues/52#issuecomment-194556173), we should not add a time signature event at tick 0 when there are time signature events present, as we currently do [here](https://github.com/craffel/pretty-midi/blob/master/pretty_midi/pretty_midi.py#L910).

**Comment by craffel** [comment]
@douglaseck if this is solved in be708952832d5571c2e127370620e56ec7846dd8 can you close?  Thanks.

**Comment by douglaseck** [comment]
I tried by doing this:
git commit --amend -m "Add a comparator for sorting a track that handles
all event types. Fixes #61"
git pull
git push origin master

So I think that put "Fixes 61" in the commit message.

Git is becoming less magical as I use it, but the less magical it becomes,
the more I'm somewhat annoyed by it. I'm sure I'll learn. There's got to be
a good reason it took over the world.  There's got to be a reason you can't
just close an open issue by clicking "Close" somewhere on the issue . ..

**Comment by craffel** [comment]
So, that would work on your own fork; you can only push commits to your fork of `pretty-midi`, not my fork.  There is indeed a "close" button, it's next to the "comment" button on the issues page:
https://github.com/craffel/pretty-midi/issues/61
You are getting me curious as to how they do things internally at Google...

**Comment by douglaseck** [comment]
But I think that close button only shows up for the owner of the issue. See
attached screenshot of what I see.

**Comment by craffel** [comment]
Oops, sorry, I had thought you had opened this issue (you just reported it).  I'll close it!

**Comment by douglaseck** [comment]
So git/github is not all that crazy after all :-)

**Comment by craffel** [comment]
Haha, yeah, just me...
