### ISSUE TITLE
Time is not a float. Note timings are sometimes float, sometimes np.float64

### ISSUE THREAD

**Issue by douglaseck** [craffel/pretty-midi#63]
https://github.com/craffel/pretty-midi/blob/master/pretty_midi/containers.py#L17
In fact there's an explicit test which raises an error if time is a float. It seems to be an np.float64. This is just a documentation issue. However it raises a question: do you intend for note.start and note.end to be np.float64 or to be float? The documentation says float, but in fact you get np.float64 values.  This has caused us some problems in going back and forth between protos and PrettyMIDI instances.  I believe the transformation from float to np.float64 happens when timing is manipulated via self.__tick_to_time = np.zeros(max_tick + 1)  (this default constructor does yield an np array of type np.float64). 

In [1]: import pretty_midi

In [2]: x = pretty_midi.Note(10, 10, 1.00, 1.00)

In [3]: type(x.start)
Out[3]: float

In [4]: mf = pretty_midi.PrettyMIDI('/tmp/example.mid')
Reading /tmp/example.mid

In [5]: type(mf.instruments[0].notes[0].start)
Out[5]: numpy.float64

**Comment by craffel** [comment]
Well, technically a `np.float64` is a `float`, in the `isinstance` sense:
```Python
>>> a = np.float64(3.3)
>>> type(a)
numpy.float64
>>> isinstance(a, float)
True
```
In order to stay sane I usually make the assumption that `np.float64` can be used interchangeably with `float`.  Code which doesn't do make this assumption bums me out but does exist (Theano is a good example).  I don't think it would do any harm to be more explicit about casting things to `float`, if that would fix the issue you're experiencing.  But, I'd also gently suggest that the other code you're using which considers `np.float64` and `float` different should maybe be changed too.

**Comment by douglaseck** [comment]
I can fix this on my side by treating note timings as c++ doubles not
floats.

That said, the documentation error stands :-) The time is documented as a
float. Then you explicitly raise an exception if a float is passed in.

**Comment by craffel** [comment]
> That said, the documentation error stands :-) The time is documented as a
float. 

Well, my policy is usually that the specified type in the docstring implies that the actual type will satisfy `isinstance(thing, type)`.  

> Then you explicitly raise an exception if a float is passed in.

Which exception do you mean?  If it's raising an Exception when a float is passed in, that's definitely a bug!

**Comment by douglaseck** [comment]
I misunderstood something about floats. I thought an np.float32 was a
python float. It turns out it's not.  Only 64-bit floats evaluate to true
for isinstance(x, float).  So your code is fine. I just need to switch my
code to use c++ doubles, not c++ floats.

Sorry for the confusion.

**Comment by craffel** [comment]
>  I thought an np.float32 was a python float. It turns out it's not.

That's interesting, I also didn't realize `isinstance(np.float32(3.1), float)` evaluates to False.  I guess it makes sense.  I'll close this issue, feel free to reopen if you find any other problems here.
