### ISSUE TITLE
time_to_tick generates incorrect timing due to casting from float to int.

### ISSUE THREAD

**Issue by douglaseck** [craffel/pretty-midi#64]
time_to_tick does return int(tick) at the end. But it should be round(int(tick)). 

I attached an example midi file. It's a metronome with a tempo map. 
[example.zip](https://github.com/craffel/pretty-midi/files/242900/example.zip)
If you mididump.py the file you'll see that all NoteOn events have tick=360 and all NoteOffs have tick=120

If you read it and write it:
pretty_midi.PrettyMIDI('/tmp/example_accel.mid').write('/tmp/testing.mid')
you'll see that one of the NoteOn events has a tick=359 and one of the NoteOffs has a tick=121

If you change time_to_tick to be round(int(tick)) the timing is correct. 

I haven't thought this through. It could be that rounding will introduce unintended problems elsewhere.

**Comment by craffel** [comment]
You're right, thanks.  I would think that `int(round(tick))` would have the fewest side-effects, but it's worth investigating.

**Comment by douglaseck** [comment]
PS in the incorrect version the NoteOff had a tick of 121. The total length of the track is not (luckily) wrong.  Regardless, agreed.  I'll not bother doing a pull request for a one-line fix. 

I'd fix it in our internal version and wait for the next release :-)

**Comment by craffel** [comment]
If this was fixed in 1920865fe70b912b7e02318d76f7411b7258a6fe can you close?  Thanks.
