### ISSUE TITLE
Had trouble importing pretty_midi on Ubuntu

### ISSUE THREAD

**Issue by Javie1127** [craffel/pretty-midi#69]
![image](https://cloud.githubusercontent.com/assets/17323872/16591160/976ff062-42a8-11e6-99f2-8fa6a1b427b1.png

![image](https://cloud.githubusercontent.com/assets/17323872/16596938/3f07e83c-42c4-11e6-9cb9-2229ff685fc5.png)

I don't know why this message keeps popping up when I was running my script on ananconda2 on Ubuntu (Picture 1). I can import pretty_midi normally in python console but not in IPython console either (Picture 2). 

Could anyone help me out with the issue above?

**Comment by craffel** [comment]
This looks like an issue with Anaconda/libreadline, not `pretty_midi`, it is being reported by a handful of people on Google.  You could try http://stackoverflow.com/questions/29944238/importerror-when-using-rpy2-with-numpy-testing or see https://github.com/ContinuumIO/anaconda-issues/issues/152  Good luck!
