### ISSUE TITLE
Store lyrics events

### ISSUE THREAD

**Issue by craffel** [craffel/pretty-midi#72]
Should be a simple container with time and text, populated on loading.

**Comment by amirsaffari** [comment]
I did a simple implementation here:

https://github.com/amirsaffari/pretty-midi/blob/dev/pretty_midi/pretty_midi.py#L314

Happy to make a PR if you need.

**Comment by craffel** [comment]
Cool!  There are a few other misc things which would need to be added - adjusting the timing of the lyrics events in `adjust_times` (perticularly once #70 is merged) and writing out the lyrics events in `write`. If you want to try to take care of all of this stuff, a PR would be great, otherwise I can do it in short order!

**Comment by amirsaffari** [comment]
No worries, will take care of it (probably over the weekend).

**Comment by craffel** [comment]
Great.  You should definitely wait for #70 to be merged though!

**Comment by craffel** [comment]
Created PR #74 - @amirsaffari does this look reasonable to you?  Thanks!
