### ISSUE TITLE
Exchange fluidsynth binding with a Python 3 compatible wrapper

### ISSUE THREAD

**Issue by carlthome** [craffel/pretty-midi#96]
Unfortunately importing pretty_midi fails in Python 3 if pyfluidsynth has been installed, as it is not compatible with Python 3. Could that dependency be exchanged with a modern equivalent instead?

As to why it's possible to install `pip install pyfluidsynth` in a Python 3 environment, I don't know. :confused:

**Comment by carlthome** [comment]
This for example: https://github.com/nwhitehead/pyfluidsynth.git

**Comment by carlthome** [comment]
In progress: https://github.com/craffel/pretty-midi/pull/95#issuecomment-249606875

**Comment by craffel** [comment]
> In progress: #95 (comment)

Sorry, I was talking about `python-midi`, not `pyfluidsynth`.

`fluidsynth`/`pyfluidsynth` is a soft dependency, and I'd rather keep it that way.  I'd also rather point people to the canonical fork of `pyfluidsynth` if possible.  Maybe you can get your Python3-compatible change to `pyfluidsynth` merged upstream?  Or, you can always use this hack: https://gist.github.com/craffel/50a422f431350f0b3b09

**Comment by carlthome** [comment]
The gist will do! Thanks. 

But maybe have pyfluidsynth in `extras_require` then, at least?

**Comment by craffel** [comment]
The reason I've left it this way is because there's no way to enforce that `fluidsynth` is installed, and it doesn't make a lot of sense to get people to install `pyfluidsynth` without also installing `fluidsynth` for them.  If you know of a good way, I'm all ears.

**Comment by carlthome** [comment]
Aside from having fluidsynth in conda-forge or something, or packaging it directly with pyfluidsynth (yuk), I don't know a particularly good solution for how to handle system dependencies with Python packages. It's not unprecedented though that Python bindings require some additional `apt`, `brew`, etc. commands, but I totally agree with you.
