### ISSUE TITLE
Change parser to mido

### ISSUE THREAD

**Issue by craffel** [craffel/pretty-midi#99]
cc @douglaseck, @cghawthorne

The current backend, [`python-midi`](https://github.com/vishnubob/python-midi), does not appear very actively maintained.  The [last release was over 3 years ago](https://github.com/vishnubob/python-midi/releases), despite [63 commits](https://github.com/vishnubob/python-midi/compare/c66e93b529d4c65178c40a72096d26bd903743ac...HEAD) since then. The [current entry in PyPI](https://pypi.python.org/pypi/midi) is not installable (nothing has been uploaded).  There is [another entry in PyPI](https://pypi.python.org/pypi/python-midi), but it states that it is v0.2.4, which does not appear to be an official release, and either way is almost 2 years out of date.  The `python-midi` PyPI package also is not maintained by the actual package owner.   `pretty_midi` depends on commits to `python-midi` which have happened since v0.2.3, so `pretty_midi` is effectively not PIP-installable (not to mention the questionable nature of depending on a PyPI package which is not maintained by the package owner).  [There doesn't seem to be any activity](https://github.com/vishnubob/python-midi/issues/72#issuecomment-247674339) to solve these issues.

Alternatively, [`mido`](https://github.com/olemb/mido) also provides a pure-Python MIDI parser.  It was developed after `python-midi` was created, so using `mido` from the getgo was not an option.  It is much more actively maintained, with frequent releases, quick merging of PRs, etc.  Assuming there are no package-specific issues, we should switch to using `mido`.

**Comment by carlthome** [comment]
When mido is being used instead, could pretty-midi also expose the MIDI type? It would be very useful for a number of cases, like when synthesizing Lakh with MrsWatson for example. :smile:

**Comment by craffel** [comment]
Do you mean the MIDI file type (type 0, type 1)?  In what circumstance is this important?

**Comment by carlthome** [comment]
Yes. For example, [MrsWatson](https://github.com/teragonaudio/MrsWatson) only reads type 0 at the moment, and will halt if a type 1 is input.

**Comment by craffel** [comment]
Oh, do you mean when writing, being able to specify whether you want to output a type 0 vs type 1 MIDI?  Hm, this is out of the scope of this issue for sure (it could be implemented regardless of the backend), but we could potentially consider it.  I didn't realize there was any modern software that didn't support type 0.  That's sort of a bummer.

**Comment by craffel** [comment]
I have this mostly implemented, but I have discovered two MIDI files which are parsed differently by `mido` and `midi`, e.g.:

```Python
>>> for t in mido.MidiFile('Musica musica.mid').tracks:
...     print len(t)
...
4
1
1
7
342
1523
484
1660
682
3550
1094
1466
54

>>> for t in midi.read_midifile('Musica musica.mid'):
...     print len(t)
...
6
7
342
1523
484
1660
682
3550
1094
1466
54
720
56
```

Not sure which one is correct, or where this difference comes from.  I can investigate, but it will be slower going than work on `pretty_midi`.  @douglaseck @cghawthorne if either of you would like to investigate, I can send you the problem MIDIs.

**Comment by douglaseck** [comment]
Please send them!

**Comment by craffel** [comment]
Posted an issue on the mido repository in case they have any ideas.  https://github.com/olemb/mido/issues/62
